file_format: "1"
id: xiaocorne
name: XiaoCorne
type: shield
url: https://github.com/mali1741/zmk-config-mcorne.git
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - xiaocorne_left
  - xiaocorne_right
